### PR TITLE
Fixed window and tile resizing/scaling issue

### LINKED ISSUE #3: Number on tiles are too small
The numbers on the tiles should be bigger.  If the game is make such that the board can be resized to fit different size screens, then the number font should also be scaled to match.

### LINKED ISSUE #7: Resizing window should resize tiles
Resizing the window should resize the tiles together with the tile number. The aspect ratio should stay the same.

### PR DESCRIPTION
**Pull request by bach5000**
Fixes #3 and fixes #7 :)

### CODE REVIEW

**Comment by scottmc** [comment]
Can you make some upding screenshots showing how it looks, perhaps in the middle of the game?  Maybe even add on to the pull request to replace the one currently shown in the readme.md

File: NumberView.cpp [hunk 1]
```diff
@@ -8,16 +8,23 @@
 #include <String.h>
 #include <iostream>
 
+float squareSize = 100;
+
+void SetScale (float scale)
+{
+	squareSize *= scale;
```
Comment (pulkomandy) [inline NumberView.cpp]: Are you sure it shouldn't be squareSize = 100 * scale ? What happens if that method is called muliple times?
If applying a factor is really what you mean, then the method should be called ScaleBy instead.

File: NumberView.cpp [hunk 2]
```diff
@@ -30,6 +37,14 @@ NumberView::SetNumber(uint32 number)
 void
 NumberView::Draw(BRect r)
 {
+	// Update squares everytime a window is resized
+	SetExplicitMinSize(BSize(squareSize, squareSize));
+	SetExplicitMaxSize(BSize(squareSize, squareSize));
+	SetExplicitPreferredSize(BSize(squareSize, squareSize));
+	BFont *font = new BFont(be_bold_font);
+	font->SetSize(squareSize/2);
+	SetFont(font);
```
Comment (pulkomandy) [inline NumberView.cpp]: This block looks very similar to the constructor. Try to not repeat yourself and factor it out in a separate method, called both here and from the constructor.
Also, it looks inefficient to do this each time Draw is called. Why not do it just once in SetScale instead?

File: WindowBoard.cpp [hunk 3]
```diff
@@ -18,6 +18,11 @@
 #include <String.h>
 #include <StringView.h>
 
+float prevWidth;
+float prevHeight;
+float defaultWidth;
+float defaultHeight;
```
Comment (pulkomandy) [inline WindowBoard.cpp]: It is bad to have global variables like this, because if any other file does the same with the same names, the variables will conflict. Could you put these inside the GameWindow class instead?

File: WindowBoard.cpp [hunk 4]
```diff
@@ -143,6 +152,24 @@ GameWindow::showBoard()
...
+	float ratio = width/prevWidth;
+	SetScale(ratio);
+	prevWidth = width;
+	prevHeight = height;
+	// Keep everything in scale and in the right width:height ratio
+	ResizeTo(width, height*ratio);
+	// We don't want the user to scale the window so small that
+	// there's no space for the buttons.
+	if (width < defaultWidth) {
+		ResizeTo(defaultWidth, defaultHeight);
```
Comment (pulkomandy) [inline WindowBoard.cpp]: When this happens, you will be calling ResizeTo twice, before and inside the if. Can you rearrange the code so that this does not happen? We want to resize only once when we are sure we got the final size.

File: NumberView.cpp (hunk 1 above)
Comment (bach5000) [reply NumberView.cpp]: Good suggestion! I'll rename the function.
But I would have to leave `squareSize *= scale` as it is, 
because if I changed it to `squareSize *= scale * 100`, scaling the window by a factor of 2 would scale the square tiles ... by 200 (which is definitely not what we want).

File: WindowBoard.cpp (hunk 4 above)
Comment (bach5000) [reply WindowBoard.cpp]: Oops. You're right. I'll fix this right away :)

File: WindowBoard.cpp (hunk 3 above)
Comment (bach5000) [reply WindowBoard.cpp]: Ok.

**Comment by bach5000** [comment]
@scottmc, I have the screenshots, but I have no idea how you put them on README.md :(
What do I do?

**Comment by scottmc** [comment]
for now, just add the screenshot.png to the root of the source code and from there I can then add it into the readme

**Comment by bach5000** [comment]
Okay @scottmc :)

**Comment by tuankiet65** [comment]
```
~/tmp/Haiku2048> make
mkdir -p objects.x86-cc2-release; \
mkdepend  -I./  -Iobjects.x86-cc2-release/ -p .cpp:objects.x86-cc2-release/%n.o -m -f "objects.x86-cc2-release/WindowBoard.d" WindowBoard.cpp
g++ -c WindowBoard.cpp  -I./  -Iobjects.x86-cc2-release/ -I-   -O3    -o "objects.x86-cc2-release/WindowBoard.o"
/boot/home/tmp/Haiku2048/WindowBoard.cpp: In method `void GameWindow::FrameResized(float, float)':
/boot/home/tmp/Haiku2048/WindowBoard.cpp:189: implicit declaration of function `int SetScale(...)'
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86-cc2-release/WindowBoard.o' failed
make: *** [objects.x86-cc2-release/WindowBoard.o] Error 1
```

**Comment by bach5000** [comment]
Ooof. I didn't notice until now. The "SetScale" function should be "ScaleBy" in WindowBoard.cpp,  method GameWindow::FrameResized. I'm really sorry to cause all this chaos :(
